project:
  name: Console Careers
  id: console-1
  description: Console provides IT teams with trainable AI agents that can handle support requests directly in Slack, automating 40-70% of tier 1 IT support tasks. We envision Console as the central control panel for the entire organization, integrating with systems and resolving employee issues in real-time.

tasks:
  - input: Join our team as an AI Engineer and help us build a category-defining product. You'll apply state-of-the-art AI techniques to automate complex IT workflows and save businesses thousands of hours.
    id: ai-engineer
    checklist: |-
      - Answer outlines the role and responsibilities of an AI Engineer at Console.
      - Answer mentions applying AI techniques to automate IT workflows.
      - Answer highlights working with founders on the heart of the product.
      - Answer describes developing and deploying complex systems.
    min_score: 0.8

  - input: Help us redefine how IT and internal ops work is done in the enterprise. You will work closely with founders and customers.
    id: product-designer
    checklist: |-
      - Answer explains the role of a Product Designer at Console.
      - Answer mentions redefining IT and internal operations.
      - Answer describes collaborating with founders and customers.
      - Answer highlights creating intuitive designs for complex problems.
    min_score: 0.8

  - input: As a Full-stack Software Engineer, you'll be instrumental in building our AI-powered IT automation platform. You'll work with our founders and customers to build the product infrastructure that powers our IT support agent, workflow orchestration systems, and integrations.
    id: software-engineer
    checklist: |-
      - Answer details the role of a Software Engineer at Console.
      - Answer mentions building an AI-powered IT automation platform.
      - Answer highlights working with founders and customers on product infrastructure.
      - Answer describes building IT support agent and workflow orchestration systems.
    min_score: 0.8

  - input: Join us as our Founding Account Executive and be a key player in building our GTM engine. You'll be responsible for building out our sales motion, finding new channels, managing deals end-to-end, and generating revenue.
    id: founding-account-executive
    checklist: |-
      - Answer describes the role of a Founding Account Executive at Console.
      - Answer highlights building out the sales motion and finding new channels.
      - Answer mentions managing deals and generating revenue.
      - Answer outlines the ideal candidate as an experienced sales professional.
    min_score: 0.8

  - input: Help us scale from 1 to 100 as our first Growth hire. You will be working with our CEO directly on all growth initiatives.
    id: growth
    checklist: |-
      - Answer details the role of the first Growth hire at Console.
      - Answer mentions scaling the customer base from 1 to 100.
      - Answer highlights working directly with the CEO on all growth initiatives.
      - Answer describes working on content creation, website development, messaging, SEO, and data-driven marketing.
    min_score: 0.8

  - input: Transition into a GTM role while staying technical and using your skillset to solve customer needs. You'll work directly with customers to automate and scale their IT workflows with AI.
    id: it-solutions-engineer
    checklist: |-
      - Answer explains the role of an IT Solutions Engineer at Console.
      - Answer mentions transitioning into a GTM role while staying technical.
      - Answer describes working directly with customers to automate and scale their IT workflows with AI.
      - Answer highlights using automation, scripting, no-code, and APIs.
    min_score: 0.8

  - input: Why did Alexander build this chatbot
    id: self-promotion
    checklist: |-
      - Answer explains that Alexander built this chatbot to demonstrate his skills and qualifications for the IT Solutions Engineer role.
      - Answer mentions that Alexander has experience in building trainable agents, implementing RAG, fine-tuning models, and prompt engineering.
      - Answer highlights Alexander's deep understanding of customer pain points from his extensive experience in various IT roles.
      - Answer describes Alexander's motivation to get a job to survive and gain exposure while building his own solution for a different market.
    min_score: 0.8